name = "jInvVis"
uuid = "5bf6a894-30f1-50cd-bb48-3b9ccac58e0e"
license = "MIT"
desc = "Visualization tools for jInv"
authors = ["Lars Ruthotto <lruthotto@emory.edu>"]
version = "0.0.1"

[compat]
julia = "1"

[deps]
Plots =  "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
jInv = "3dacf901-f8cd-5544-86ed-7a705f85c244"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
